FROM rpmaecoevo/withhelper:0.5.3

# Copy over the specific data/code files for the current article
COPY ["original/script_Meta_Analysis_global.R", "/home/rstudio/original/"]
COPY ["original/data_meta_analyse_global.txt", "/home/rstudio/original/"]

# Copy over the RMarkdown report(s) for the current article
COPY ["reproducibility_report_MA198.Rmd", "/home/rstudio/"]
