FROM rpmaecoevo/withhelper:0.5.3

# Copy over the specific data/code files for the current article
COPY ["original/Script_Forest areas.R", "/home/rstudio/original/"]
COPY ["original/Biomass_Forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Birds_Forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Cover_Forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Density_Forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Height_Forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Herpeto_Forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Invertebrates_Forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Litter_Forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Mammals_Forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Plants_Forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Script_Contiguous forest areas.R", "/home/rstudio/original/"]
COPY ["original/Biomass_Contiguous_forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Birds_Contiguous_forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Cover_Contiguous_forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Density_Contiguous_forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Height_Contiguous_forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Herpeto_Contiguous_forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Invertebrates_Contiguous_forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Litter_Contiguous_forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Mammals_Contiguous_forest_areas.txt", "/home/rstudio/original/"]
COPY ["original/Plants_Contiguous_forest_areas.txt", "/home/rstudio/original/"]

# Copy over the RMarkdown report(s) for the current article
COPY ["reproducibility_report_MA129.Rmd", "/home/rstudio/"]
