FROM rpmaecoevo/withhelper:0.5.3

# Copy over the specific data/code files for the current article
COPY ["original/ele12804-sup-0003-appendixa2.xlsx", "/home/rstudio/original/"]

# Copy over the RMarkdown report for the current article
COPY ["reproducibility_report_MA016.Rmd", "/home/rstudio/"]
