FROM rpmaecoevo/withhelper:0.5.3

# Copy over the specific data/code files for the current article
COPY ["original/brv12358-sup-0002-appendixs2_ms.r", "/home/rstudio/original/"]
COPY ["original/brv12358-sup-0001-appendixs1.xls", "/home/rstudio/original/"]


# Copy over the RMarkdown report(s) for the current article
COPY ["reproducibility_report_MA071.Rmd", "/home/rstudio/"]
