FROM rpmaecoevo/withhelper:0.5.3

# Copy over the specific data/code files for the current article
COPY ["original/nph13693-sup-0001-methods1.pdf", "/home/rstudio/original/"]
COPY ["original/nph13693-sup-0003-notess2.txt", "/home/rstudio/original/"]
COPY ["original/nph13693-sup-0004-notess3.new", "/home/rstudio/original/"]

# Copy over the RMarkdown report for the current article
COPY ["reproducibility_report_MA126.Rmd", "/home/rstudio/"]
