FROM rpmaecoevo/withhelper:0.5.3

# Copy over the specific data/code files for the current article
COPY ["original/brv12387-sup-0001-appendixs1.xlsx", "/home/rstudio/original/"]
COPY ["original/brv12387-sup-0002-appendixs2.r", "/home/rstudio/original/"]

# Copy over the RMarkdown report for the current article
COPY ["reproducibility_report_MA062.Rmd", "/home/rstudio/"]
