FROM rpmaecoevo/withhelper:0.5.3

# Copy over the specific data/code files for the current article
COPY ["original/SpatialStructure_Analysis.R", "/home/rstudio/original/"]
COPY ["original/SpatialStructure_Data.csv", "/home/rstudio/original/"]

# Copy over the RMarkdown report(s) for the current article
COPY ["reproducibility_report_MA213.Rmd", "/home/rstudio/"]
