FROM rpmaecoevo/withhelper:0.5.3

# Copy over the specific data/code files for the current article
COPY ["original/allometry_data.xlsx", "/home/rstudio/original/"]
COPY ["original/running all models in table 2.txt", "/home/rstudio/original/"]

# Copy over the RMarkdown report(s) for the current article
COPY ["reproducibility_report_MA191.Rmd", "/home/rstudio/"]
