FROM rpmaecoevo/withhelper:0.5.3

# Copy over the specific data/code files for the current article
COPY ["original/Q1All.csv", "/home/rstudio/original/"]
COPY ["original/Q1 standard and multilevel.R", "/home/rstudio/original/"]


# Copy over the RMarkdown report(s) for the current article
COPY ["reproducibility_report_MA074.Rmd", "/home/rstudio/"]
