FROM rpmaecoevo/withhelper:0.5.3

# Copy over the specific data/code files for the current article
COPY ["original/nph13238-sup-0001-tables1.xlsx", "/home/rstudio/original/"]
COPY ["original/nph13238-sup-0004-notess2.r", "/home/rstudio/original/"]

# Copy over the RMarkdown report(s) for the current article
COPY ["reproducibility_report_MA202.Rmd", "/home/rstudio/"]
